version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 22
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-power-select
    versions:
    - ">=3"
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.2
    - 10.2.0
    - 10.3.0
    - 10.4.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: ember-cli-babel
    versions:
    - 7.23.1
    - 7.24.0
    - 7.25.0
    - 7.26.0
    - 7.26.1
    - 7.26.2
    - 7.26.3
  - dependency-name: ember-auto-import
    versions:
    - 1.10.1
    - 1.11.0
    - 1.11.1
    - 1.11.2
  - dependency-name: ember-source
    versions:
    - 3.24.1
    - 3.25.0
    - 3.25.1
    - 3.25.2
    - 3.25.3
    - 3.26.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.1
    - 5.3.2
    - 5.4.0
    - 5.5.0
    - 5.6.0
    - 5.6.1
    - 5.6.2
    - 5.6.3
    - 5.6.4
    - 5.6.5
    - 5.7.0
  - dependency-name: ember-changeset
    versions:
    - 3.10.5
    - 3.11.0
    - 3.12.0
    - 3.13.0
    - 3.13.1
    - 3.13.2
  - dependency-name: ember-changeset-validations
    versions:
    - 3.10.3
    - 3.11.0
    - 3.12.0
    - 3.13.0
    - 3.14.0
    - 3.14.1
  - dependency-name: ember-router-scroll
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: elliptic
    versions:
    - 6.5.3
